# Generated by Django 5.0.2 on 2024-03-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0002_rename_matchball_matchdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchData',
        ),
    ]
